﻿﻿apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workflows.cloud-flows.io
spec:
  scope: Namespaced
  group: cloud-flows.io
  names:
    plural: workflows
    singular: workflow
    kind: Workflow
    shortNames:
    - wf
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties: {} #todo
          required:
            - spec