apiVersion: apps/v1
kind: Deployment
metadata:
  name: garnet
  namespace: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garnet
  template:
    metadata:
      labels:
        app: garnet
    spec:
      containers:
        - name: garnet
          image: ghcr.io/microsoft/garnet
          ports:
            - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: garnet
  namespace: synapse
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: garnet
  type: ClusterIP