apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: synapse
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-role-binding
subjects:
- kind: ServiceAccount
  name: operator
  namespace: synapse
roleRef:
  kind: ClusterRole
  name: operator-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-1
  namespace: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: operator
      containers:
        - name: operator
          image: ghcr.io/serverlessworkflow/synapse/operator:1.0.0-alpha1
          env:
            - name: CONNECTIONSTRINGS__REDIS
              value: garnet:6379
            - name: SYNAPSE_OPERATOR_NAMESPACE
              value: default
            - name: SYNAPSE_OPERATOR_NAME
              value: operator-1
            - name: SYNAPSE_RUNNER_API
              value: http://api:8080
            - name: SYNAPSE_RUNNER_LIFECYCLE_EVENTS
              value: "true"
            - name: SYNAPSE_RUNNER_CONTAINER_PLATFORM
              value: kubernetes
            - name: SYNAPSE_RUNTIME_MODE
              value: kubernetes
            - name: SYNAPSE_RUNTIME_K8S_SERVICE_ACCOUNT
              value: operator
            - name: SYNAPSE_RUNTIME_K8S_NAMESPACE
              value: synapse
---

apiVersion: v1
kind: Service
metadata:
  name: operator
  namespace: synapse
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: operator
  type: ClusterIP
